-- =====================================================================
-- V10__device_monitoring.sql
--
-- Backs the new com.haodaone.monitoring module: server-side support for
-- the HaodaOne.Agent Windows service (per-device activity/heartbeat
-- monitoring). Two new tables, matching MonitoredDevice.java and
-- ActivitySession.java exactly, same as every migration since
-- spring.jpa.hibernate.ddl-auto=validate stopped auto-creating anything
-- (see V9 for the same note). Nothing existing is touched.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.monitored_device (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                     bigint NOT NULL DEFAULT 0,
    created_at                  timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at                  timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by                  character varying(100),
    updated_by                  character varying(100),
    deleted                     boolean NOT NULL DEFAULT false,
    deleted_at                  timestamp(6) without time zone,
    device_id                   character varying(100) NOT NULL,
    device_name                 character varying(150) NOT NULL,
    windows_username             character varying(150),
    domain_name                 character varying(150),
    ip_address                  character varying(50),
    mac_address                 character varying(50),
    operating_system            character varying(100),
    os_version                  character varying(50),
    agent_version               character varying(50),
    agent_token_hash            character varying(200) NOT NULL,
    employee_id                 bigint REFERENCES public.employee(id),
    status                      character varying(20) NOT NULL DEFAULT 'OFFLINE',
    current_application         character varying(255),
    current_window_title        character varying(500),
    last_seen_at                timestamp(6) without time zone,
    last_ip_address             character varying(50),
    active                      boolean NOT NULL DEFAULT true,
    heartbeat_interval_seconds  integer,
    monitoring_paused           boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_monitored_device_device_id UNIQUE (device_id),
    CONSTRAINT uq_monitored_device_token_hash UNIQUE (agent_token_hash)
);

CREATE INDEX IF NOT EXISTS idx_monitored_device_employee_id ON public.monitored_device (employee_id);

-- Powers the "which devices are offline" dashboard widget without a full
-- table scan on every poll, same rationale as V9's expiry_date index.
CREATE INDEX IF NOT EXISTS idx_monitored_device_last_seen_at ON public.monitored_device (last_seen_at);

CREATE TABLE IF NOT EXISTS public.activity_session (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             bigint NOT NULL DEFAULT 0,
    created_at          timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at          timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by          character varying(100),
    updated_by          character varying(100),
    deleted             boolean NOT NULL DEFAULT false,
    deleted_at          timestamp(6) without time zone,
    session_id          character varying(40) NOT NULL,
    device_id           bigint NOT NULL REFERENCES public.monitored_device(id),
    employee_id         bigint REFERENCES public.employee(id),
    process_name        character varying(255),
    application_name    character varying(255),
    window_title        character varying(500),
    start_time          timestamp(6) without time zone NOT NULL,
    end_time            timestamp(6) without time zone,
    duration_seconds    integer NOT NULL DEFAULT 0,
    is_idle_session     boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_activity_session_session_id UNIQUE (session_id)
);

CREATE INDEX IF NOT EXISTS idx_activity_session_device_id ON public.activity_session (device_id);
CREATE INDEX IF NOT EXISTS idx_activity_session_employee_id ON public.activity_session (employee_id);

-- Powers per-device and org-wide "activity in this date range" queries
-- (Monitoring dashboard + reports) - without this, both do a full table
-- scan on start_time every time they run.
CREATE INDEX IF NOT EXISTS idx_activity_session_start_time ON public.activity_session (start_time);
