-- =====================================================================
-- V2__new_hrms_module_tables.sql
--
-- Tables for HaodaOne's Performance and Recruitment modules. Nothing in
-- the HaodaAsset schema covers goals, performance reviews, job openings,
-- candidates, or interviews, so - per the "only create new tables when
-- absolutely required for new HRMS modules" rule - these five are new.
-- Everything else HaodaOne needs (employee, department, designation,
-- team, role, permission, app_user, leave_*, attendance_*, audit_log,
-- login_history, refresh_token, biometric_device) is reused from
-- HaodaAsset directly; see V1 for the small additive changes those
-- needed.
--
-- Column shapes match HaodaOne's JPA entities exactly (Goal,
-- PerformanceReview, JobOpening, Candidate, Interview) since
-- spring.jpa.hibernate.ddl-auto=validate no longer creates anything.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.goal (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           bigint NOT NULL DEFAULT 0,
    created_at        timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at        timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by        character varying(100),
    updated_by        character varying(100),
    deleted           boolean NOT NULL DEFAULT false,
    deleted_at        timestamp(6) without time zone,
    employee_id       bigint NOT NULL REFERENCES public.employee(id),
    title             character varying(200) NOT NULL,
    description       character varying(1000),
    target_date       date,
    status            character varying(20) NOT NULL DEFAULT 'NOT_STARTED',
    progress_percent  integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_goal_employee_id ON public.goal (employee_id);

CREATE TABLE IF NOT EXISTS public.performance_review (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                bigint NOT NULL DEFAULT 0,
    created_at             timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at             timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by             character varying(100),
    updated_by             character varying(100),
    deleted                boolean NOT NULL DEFAULT false,
    deleted_at             timestamp(6) without time zone,
    employee_id            bigint NOT NULL REFERENCES public.employee(id),
    reviewer_employee_id   bigint REFERENCES public.employee(id),
    review_period          character varying(50) NOT NULL,
    rating                 integer,
    strengths              character varying(2000),
    areas_for_improvement  character varying(2000),
    status                 character varying(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at           timestamp(6) without time zone
);
CREATE INDEX IF NOT EXISTS idx_performance_review_employee_id ON public.performance_review (employee_id);

CREATE TABLE IF NOT EXISTS public.job_opening (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          bigint NOT NULL DEFAULT 0,
    created_at       timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at       timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by       character varying(100),
    updated_by       character varying(100),
    deleted          boolean NOT NULL DEFAULT false,
    deleted_at       timestamp(6) without time zone,
    title            character varying(150) NOT NULL,
    department_id    bigint REFERENCES public.department(id),
    designation_id   bigint REFERENCES public.designation(id),
    employment_type  character varying(20) NOT NULL DEFAULT 'FULL_TIME',
    openings_count   integer NOT NULL DEFAULT 1,
    status           character varying(20) NOT NULL DEFAULT 'OPEN',
    description      character varying(2000),
    posted_date      date,
    closed_date      date
);

CREATE TABLE IF NOT EXISTS public.candidate (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                bigint NOT NULL DEFAULT 0,
    created_at             timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at             timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by             character varying(100),
    updated_by             character varying(100),
    deleted                boolean NOT NULL DEFAULT false,
    deleted_at             timestamp(6) without time zone,
    first_name             character varying(100) NOT NULL,
    last_name              character varying(100) NOT NULL,
    email                  character varying(150) NOT NULL,
    phone                  character varying(30),
    job_opening_id         bigint NOT NULL REFERENCES public.job_opening(id),
    source                 character varying(100),
    resume_url             character varying(500),
    stage                  character varying(20) NOT NULL DEFAULT 'APPLIED',
    applied_date           date NOT NULL,
    offer_amount           double precision,
    expected_joining_date  date,
    notes                  character varying(1000)
);
CREATE INDEX IF NOT EXISTS idx_candidate_job_opening_id ON public.candidate (job_opening_id);

CREATE TABLE IF NOT EXISTS public.interview (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                   bigint NOT NULL DEFAULT 0,
    created_at                timestamp(6) without time zone NOT NULL DEFAULT now(),
    updated_at                timestamp(6) without time zone NOT NULL DEFAULT now(),
    created_by                character varying(100),
    updated_by                character varying(100),
    deleted                   boolean NOT NULL DEFAULT false,
    deleted_at                timestamp(6) without time zone,
    candidate_id              bigint NOT NULL REFERENCES public.candidate(id),
    interviewer_employee_id   bigint REFERENCES public.employee(id),
    scheduled_at              timestamp(6) without time zone NOT NULL,
    mode                      character varying(20) NOT NULL DEFAULT 'VIDEO',
    status                    character varying(20) NOT NULL DEFAULT 'SCHEDULED',
    rating                    integer,
    feedback                  character varying(1000)
);
CREATE INDEX IF NOT EXISTS idx_interview_candidate_id ON public.interview (candidate_id);
